# Generated by Django 4.0.6 on 2022-08-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_STT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
